[package]
name = "amurta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
colored = "2"
regex = {version = "1.7.0", features = ["pattern"]}
